package br.com.harvian.comserialarduino;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 *
 * @author Harvian
 */
public class JFInterface extends javax.swing.JFrame {

    private final ControlePorta arduino;
    //variaveis de estado dos botoes de pinos digitais, iniciando como false (desligado)
    boolean estado1 = false;
    boolean estado2 = false;
    boolean estado3 = false;
    boolean estado4 = false;
    boolean estado5 = false;
    boolean estado6 = false;

    /**
     * Creates new form JFInterface
     */
    public JFInterface() {

        arduino = new ControlePorta("COM3", 9600);
        initComponents();
        
        //iniciando labels como desligado
        jLabel1.setText("Desligado!");
        jLabel2.setText("Desligado!");
        jLabel3.setText("Desligado!");
        jLabel4.setText("Desligado!");
        jLabel5.setText("Desligado!");
        jLabel6.setText("Desligado!");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonPin2 = new javax.swing.JButton();
        ButtonPin4 = new javax.swing.JButton();
        butsair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        slider2 = new javax.swing.JSlider();
        slider3 = new javax.swing.JSlider();
        slider4 = new javax.swing.JSlider();
        slider5 = new javax.swing.JSlider();
        slider6 = new javax.swing.JSlider();
        ButtonPin7 = new javax.swing.JButton();
        ButtonPin8 = new javax.swing.JButton();
        ButtonPin12 = new javax.swing.JButton();
        ButtonPin13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Com. Serial");

        buttonPin2.setText("Pino 2");
        buttonPin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPin2MouseClicked(evt);
            }
        });
        buttonPin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPin2ActionPerformed(evt);
            }
        });

        ButtonPin4.setText("Pino 4");
        ButtonPin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPin4MouseClicked(evt);
            }
        });
        ButtonPin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPin4ActionPerformed(evt);
            }
        });

        butsair.setText("Sair");
        butsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butsairMouseClicked(evt);
            }
        });
        butsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsairActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        slider1.setMaximum(255);
        slider1.setPaintTicks(true);
        slider1.setToolTipText("");
        slider1.setValue(0);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });

        slider2.setMaximum(255);
        slider2.setPaintTicks(true);
        slider2.setToolTipText("");
        slider2.setValue(0);
        slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider2StateChanged(evt);
            }
        });

        slider3.setMaximum(255);
        slider3.setPaintTicks(true);
        slider3.setValue(0);
        slider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider3StateChanged(evt);
            }
        });

        slider4.setMaximum(255);
        slider4.setPaintTicks(true);
        slider4.setValue(0);
        slider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider4StateChanged(evt);
            }
        });

        slider5.setMaximum(255);
        slider5.setPaintTicks(true);
        slider5.setValue(0);
        slider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider5StateChanged(evt);
            }
        });

        slider6.setMaximum(255);
        slider6.setPaintTicks(true);
        slider6.setValue(0);
        slider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider6StateChanged(evt);
            }
        });

        ButtonPin7.setText("Pino 7");
        ButtonPin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPin7ActionPerformed(evt);
            }
        });

        ButtonPin8.setText("Pino 8");
        ButtonPin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPin8ActionPerformed(evt);
            }
        });

        ButtonPin12.setText("Pino 12");
        ButtonPin12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPin12ActionPerformed(evt);
            }
        });

        ButtonPin13.setText("Pino 13");
        ButtonPin13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPin13ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Controle de pinos Arduino");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Pinos Digitais");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Pinos analógicos (PWM)");

        jLabel10.setText("Pino 3");

        jLabel11.setText("Pino 5");

        jLabel12.setText("Pino 6");

        jLabel13.setText("Pino 9");

        jLabel14.setText("Pino 10");

        jLabel15.setText("Pino 11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonPin7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPin8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPin12, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(ButtonPin13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butsair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPin2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ButtonPin4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPin7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPin8)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPin12)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ButtonPin13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(butsair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


  private void buttonPin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPin2MouseClicked
  }//GEN-LAST:event_buttonPin2MouseClicked

  private void ButtonPin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPin4MouseClicked
  }//GEN-LAST:event_ButtonPin4MouseClicked

  private void butsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butsairMouseClicked
      //botão de saída
      System.exit(0);//fecha a aplicação
  }//GEN-LAST:event_butsairMouseClicked

    private void butsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsairActionPerformed
    }//GEN-LAST:event_butsairActionPerformed

    private void buttonPin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPin2ActionPerformed
            //botão pino 2
        if (estado1 == false) {
            arduino.enviaDadosSt("A1" + "\n");
            estado1 = true;
            jLabel1.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("A0" + "\n");
            estado1 = false;
            jLabel1.setText("Desligado!");
        }


    }//GEN-LAST:event_buttonPin2ActionPerformed

    private void ButtonPin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPin4ActionPerformed
            //botão pino 4
        if (estado2 == false) {
            arduino.enviaDadosSt("B1"+"\n");
            estado2 = true;
            jLabel2.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("B0"+"\n");
            estado2 = false;
            jLabel2.setText("Desligado!");
        }
    }//GEN-LAST:event_ButtonPin4ActionPerformed

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
            //slider 1
        arduino.enviaDadosSt("G" + slider1.getValue() + "\n");

    }//GEN-LAST:event_slider1StateChanged

    private void slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider2StateChanged
            //slider 2
        arduino.enviaDadosSt("H" + slider2.getValue() + "\n");

    }//GEN-LAST:event_slider2StateChanged

    private void ButtonPin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPin7ActionPerformed
            //botão pino 7  
        if (estado3 == false) {
            arduino.enviaDadosSt("C1" + "\n");
            estado3 = true;
            jLabel3.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("C0" + "\n");
            estado3 = false;
            jLabel3.setText("Desligado!");
        }
    }//GEN-LAST:event_ButtonPin7ActionPerformed

    private void ButtonPin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPin8ActionPerformed
            //botão pino 8
        if (estado4 == false) {
            arduino.enviaDadosSt("D1" + "\n");
            estado4 = true;
            jLabel4.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("D0" + "\n");
            estado4 = false;
            jLabel4.setText("Desligado!");
            }
    }//GEN-LAST:event_ButtonPin8ActionPerformed

    private void ButtonPin12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPin12ActionPerformed
            //botão pino 12
        if (estado5 == false) {
            arduino.enviaDadosSt("E1" + "\n");
            estado5 = true;
            jLabel5.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("E0" + "\n");
            estado5 = false;
            jLabel5.setText("Desligado!");
        }
    }//GEN-LAST:event_ButtonPin12ActionPerformed

    private void ButtonPin13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPin13ActionPerformed
            //botão pino 13
        if (estado6 == false) {
            arduino.enviaDadosSt("F1" + "\n");
            estado6 = true;
            jLabel6.setText("Ligado!");
        } else {
            arduino.enviaDadosSt("F0" + "\n");
            estado6 = false;
            jLabel6.setText("Desligado!");
        }
    }//GEN-LAST:event_ButtonPin13ActionPerformed

    private void slider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider3StateChanged
           //slider 3
        arduino.enviaDadosSt("I" + slider3.getValue() + "\n");
        
    }//GEN-LAST:event_slider3StateChanged

    private void slider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider4StateChanged
            //slider 4
        arduino.enviaDadosSt("J" + slider4.getValue() + "\n");

    }//GEN-LAST:event_slider4StateChanged

    private void slider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider5StateChanged
            //slider 5
        arduino.enviaDadosSt("K" + slider5.getValue() + "\n");

    }//GEN-LAST:event_slider5StateChanged

    private void slider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider6StateChanged
            //slider 6
        arduino.enviaDadosSt("L" + slider6.getValue() + "\n");

    }//GEN-LAST:event_slider6StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPin12;
    private javax.swing.JButton ButtonPin13;
    private javax.swing.JButton ButtonPin4;
    private javax.swing.JButton ButtonPin7;
    private javax.swing.JButton ButtonPin8;
    private javax.swing.JButton butsair;
    private javax.swing.JButton buttonPin2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JSlider slider3;
    private javax.swing.JSlider slider4;
    private javax.swing.JSlider slider5;
    private javax.swing.JSlider slider6;
    // End of variables declaration//GEN-END:variables
}
